version: "3"

services:
    nodejs:
        build: .
        image: nodejs
        restart: unless-stopped
        environment:
            - PORT=8080
            - MONGO_URI=mongodb://mongo:27017/simple_auth
        ports:
            - "8080:8080"
        networks:
            - app-network
        command: ./wait-for-it.sh mongo:27017 -- node server.js

    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE
        volumes:
            - dbdata:/data/db
        networks:
            - app-network
        ports:
            - '27017-27019:27017-27019'

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules: