version: "3.9"
services:
    web:
        container_name: simple-auth-server
        build: .
        ports:
            - '8080:8080'
        links:
            - mongo
        environment:
            - PORT=8080
            - MONGO_URI=mongodb://mongo:27017/simple_auth
            - TOKEN_SECRET=some-very-complicated-secret

    mongo:
        image: mongo
        container_name: simple-auth-mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: simple_auth
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - '27017-27019:27017-27019'